import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import Logo from "../assets/landing/logo.svg";
import People from "../assets/landing/people.svg";
import Teamwork from "../assets/landing/teamwork.jpg";
import Button from "../components/Button";
import NavBar from "../components/NavBar";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full">
        {/* Top Header */}
        <header
          className="
        w-full h-14 flex flex-row sticky top-0 z-50 bg-white
        justify-between items-center 
        pl-2 pr-2 
        lg:pl-24 lg:pr-24 lg:pt-8 lg:pb-8 
        md:pl-12 md:pr-12 md:pt-8 md:pb-8 "
        >
          {/* Logo and text */}
          <div className="flex flex-row items-center space-x-4">
            <Image src={Logo} alt="" width={40} height={40} />
            <span className="font-BroLink "> castroai</span>
          </div>
          {/* Nav */}
          <div className="hidden  sm:flex md:flex lg:flex md:flex-row space-x-4">
            <NavBar className="" />
            <Button>Qoute Project</Button>
          </div>
        </header>
        {/* Main Hero Section */}
        <section
          className="
        h-3/4 w-full pt-14 p-2 flex flex-col justify-center
        sm:h-2/4 sm:p-12 sm:flex-row
        md:h-1/4 md:p-12 md:flex-row
        lg:h-1/2 lg:flex-row lg:space-x-10
      "
        >
          {/* TExt */}
          <div
            className="
          flex flex-col justify-around h-full
          sm:justify-center sm:w-1/2
          md:justify-center md:w-1/2 
          lg:justify-center lg:w-1/4

          "
          >
            <p className="text-3xl font-bold text-center">
              The Remote Web Development Team You need.
            </p>
            <p className="text-center ">
              Mobile, Web, Desktop, API, Automation & Cloud Development
            </p>
          </div>
          {/* People */}
          <div className="h-full lg:w-1/4 sm:w-1/2 ">
            <Image src={People} alt="" className="h-full" />
          </div>
        </section>
        {/* About */}
        <section
          className="
        bg-darkBlue text-white h-full pt-28 p-2 
        flex flex-col justify-around
        sm:p-12 sm:flex-row sm:justify-center sm:space-x-6
        md:p-12 md:flex-row md:justify-center md:space-x-6
        lg:flex-row lg:justify-center lg:space-x-10 "
        >
          <div className="sm:w-1/2 md:w-1/2 lg:w-1/4 space-y-6">
            <p className="text-2xl">
              About <span className="font-BroLink">castroai</span>
            </p>
            <p>
              <span className="font-BroLink">castroai</span> was founded in 2021
              in the state of New York. We are a team of certified engenieers &
              designers with years of experience all working towards the same
              goal. To deliver you and your business with the highest quality
              product. We’ve already helped out many new business in making
              their dreams come true. Now it’s your turn.
            </p>
          </div>
          <div className=" sm:w-1/2 md:w-1/2 lg:w-1/4 ">
            <Image src={Teamwork} alt="" className="rounded-lg" />
          </div>
        </section>
      </div>
    </div>
  );
};

export default Home;
